# Explizite Dimension-Zuordnung (neuere Iris/Oculus-Versionen brauchen das,
# damit die world-Ordner sicher greifen)
dimension.world0=minecraft:overworld
dimension.world-1=minecraft:the_nether
dimension.world1=minecraft:the_end
